### ISSUE TITLE
Add "aoss:APIAccessAll" IAM permission to the OpenSearchCollectionPipelineRole to prevent 403 error

### ISSUE THREAD

**Issue by qisylvia** [aws-samples/aws-opensearch-ingestion-tutorials#1]
Due to this change: "You are required to add these two IAM permissions for your OpenSearch Serverless "aoss:APIAccessAll" for Data Plane API access, and "aoss:DashboardsAccessAll" for Dashboards access. You must complete this action by May 9th, 2023. Failure to add the two new IAM permissions will result in 403 errors starting on May 10th, 2023", you need to add these permissions to the OpenSearchCollectionPipelineRole.

**Comment by ksmin23** [comment]
You need to add these two IAM permissions for your OpenSearch Serverless to **your IAM User**.

- "aoss:APIAccessAll" for Data Plane API access
- "aoss:DashboardsAccessAll" for Dashboards access.

For more information, checkout README again. I added an example.
